image: Visual Studio 2019
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet publish -c Release src/Viato.Api/Viato.Api.csproj
after_build:
artifacts:
 - path: '\src\Viato.Api\bin\Release\netcoreapp3.1\publish'
   name: WebSite
   type: WebDeployPackage
clone_depth: 1
test_script:
  - cmd: dotnet test src/Viato.Api.UnitTests/Viato.Api.UnitTests.csproj
on_finish :
deploy: off
